# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa349658ee0bacb8fd3e0b51bef1b578bccb6e326c182626c852a663a59bf20a6c904e5fb442fefaa5fa2fa929072a73f8f3ce32063dafc3b68ff8c50324b83b

test:
  secret_key_base: a76ae5634f504ae00a61737d4593ecc4fa5870db9f27f61a43728fac1f71a4a777296bd622955093a09c871f592c9d9af1dd36e02cb49cee16feb7bb51f43114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
